language: python
sudo: false
python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"
 - "pypy3.5"
env:
 - DJANGO_VERSION=2.2
 - DJANGO_VERSION=3.0
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO_VERSION=3.0
    - python: "pypy3.5"
      env: DJANGO_VERSION=3.0
install:
 - python setup.py install
 - pip install -q "Django>=${DJANGO_VERSION},<${DJANGO_VERSION}.99"
 - pip install -q flake8 coverage
script:
 - ./run.sh coverage
 - ./run.sh check
